### ISSUE TITLE
独显版本HDMI能正常工作吗？ 

### ISSUE THREAD

**Issue by Ziloong** [daliansky/Lenovo-Air13-IWL-Hackintosh#1]
之前尝试过GTX笔记本Hack macOS，由于HDMI对应的是独显，在macOS上 HDMI 是无法工作的。
独显版本的 Lenovo AIr13 HDMI或者Typec视频输出是否可以正常工作呢？

**Comment by Zohar727** [comment]
我就是独显版本的AIR13  HDMI不能用

**Comment by daliansky** [comment]
可以工作,最新EFI已支持
