### ISSUE TITLE
HiDPi does not work on Big Sur, Read-only file system

### ISSUE THREAD

**Issue by gribanoveu** [daliansky/Lenovo-Air13-IWL-Hackintosh#14]
new version not work
old version:
usage: dirname path
正在备份
mkdir: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: Read-only file system
cp: directory /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup does not exist
rm: /tmp/: Permission denied
mv: rename /tmp/disable to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/: No such file or directory
chmod: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/disable: No such file or directory

**Comment by xlivans** [comment]
Terminal :
```bash
    bash -c "$(curl -fsSL https://gitee.com/xlivans/Tools/raw/master/Air13IWL-HiDPI.sh)"
```
