### ISSUE TITLE
作者加油，efi很好用

### ISSUE THREAD

**Issue by oreoft** [daliansky/Lenovo-Air13-IWL-Hackintosh#15]
rt, 谢谢大大给我们air13吃上苹果

**Comment by cutety** [comment]
你好，你的是catalina还是big sur?

**Comment by oreoft** [comment]
> 你好，你的是catalina还是big sur?

big sur

**Comment by cutety** [comment]
> > 你好，你的是catalina还是big sur?
> 
> big sur
看见你这回复我就放心上了

**Comment by oreoft** [comment]
仔细使用下来能发现少许问题，希望能够帮助作者改进
1. 开盖会卡键，某个按键不停地重复按，导致键盘失效，只能重启系统解决
2. 用着用着扬声器外放突然失效，然后只能打开系统设置里面的输出（检测到麦克风），声音恢复正常，关掉麦克风则又没声音了
