### ISSUE TITLE
使用F11把亮度调到最低后无法恢复

### ISSUE THREAD

**Issue by ApsarasX** [daliansky/Lenovo-Air13-IWL-Hackintosh#17]
复现步骤：连续敲击F11
症状：当亮度到达最低后，无法使用F12增加亮度，即使在设置-显示器里把亮度条拉到最右边，亮度条还是会马上自动滑到最左边。

**Comment by stevezz3** [comment]
可尝试删除 `config.plist` 中的 `enable-backlight-registers-fix`。这个属性非常不稳定，不建议使用。

**Comment by a1029382825** [comment]
> 可尝试删除 `config.plist` 中的 `enable-backlight-registers-fix`。这个属性非常不稳定，不建议使用。

没有这个会导致黑屏吧？

**Comment by stevezz3** [comment]
太不会了 @a1029382825

**Comment by xlivans** [comment]
尝试重置NVRAM
