### ISSUE TITLE
为什么我用这个EFI替换我的EFI, 进不了系统呢

### ISSUE THREAD

**Issue by wsa920** [daliansky/Lenovo-Air13-IWL-Hackintosh#21]
为什么我用这个EFI替换我的EFI, 进不了系统呢？
我目前13.5系统，正常使用。使用这个3.0的EFI替换原EFI后（在win下用DG删掉原EFI文件夹下的boot和OC，把这个UFI里面的BOOT和OC放进去。）开机到苹果标志过一会儿就又回到启动选择界面了。填入原来的三码，还是一样，进不了系统。reset nvram, 重建启动项，再进去还是一样

**Comment by oreoft** [comment]
这个efi很早了，是不支持macOS Ventura的，如果需要支持得进行测试修改，可是我机器我早就卖了

**Comment by xlivans** [comment]
[BIOS 设置](https://github.com/daliansky/Lenovo-Air13-IWL-Hackintosh/blob/master/BIOSConfig.md)
