### ISSUE TITLE
BCM94360CS2蓝牙无法驱动

### ISSUE THREAD

**Issue by Leochina84** [daliansky/Lenovo-Air13-IWL-Hackintosh#22]
蓝牙控制器：
  地址：	NULL
  状态：	关闭
  芯片组：	BCM_4350C2
  可被发现：	关闭
  固件版本：	v0
  支持的服务：	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT SerialPort >
  传输：	PCIe
  供应商ID：	0x004C (Apple)

**Comment by Leochina84** [comment]
测试Ventura 13 / Monterey 12，存在同样问题，wifi正常使用

**Comment by Leochina84** [comment]
软件版本：
  CoreWLAN：	16.0 (1657)
  CoreWLANKit：	16.0 (1657)
  附加菜单：	17.0 (1728)
  系统信息：	15.0 (1502)
  IO80211系列：	12.0 (1200.13.0)
  诊断：	11.0 (1163)
  AirPort实用工具：	6.3.9 (639.21)
  接口：
en0：
  卡类型：	Wi-Fi  (0x14E4, 0x117)
  固件版本：	Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1772.1)
  MAC地址：	98:01:a7:c5:92:83
  位置：	Unknown
  国家/地区代码：	#a
  支持的PHY模式：	802.11 a/b/g/n/ac
  支持的频道：	1 (2GHz), 2 (2GHz), 3 (2GHz), 4 (2GHz), 5 (2GHz), 6 (2GHz), 7 (2GHz), 8 (2GHz), 9 (2GHz), 10 (2GHz), 11 (2GHz), 12 (2GHz), 13 (2GHz), 14 (2GHz), 36 (5GHz), 40 (5GHz), 44 (5GHz), 48 (5GHz), 52 (5GHz), 56 (5GHz), 60 (5GHz), 64 (5GHz), 100 (5GHz), 104 (5GHz), 108 (5GHz), 112 (5GHz), 116 (5GHz), 120 (5GHz), 124 (5GHz), 128 (5GHz), 132 (5GHz), 136 (5GHz), 140 (5GHz), 144 (5GHz), 149 (5GHz), 153 (5GHz), 157 (5GHz), 161 (5GHz), 165 (5GHz)
  隔空投送：	支持
  “隔空投送”频道：	149
  自动解锁：	支持
  状态：	已连接

**Comment by Leochina84** [comment]
![webwxgetmsgimg](https://github.com/daliansky/Lenovo-Air13-IWL-Hackintosh/assets/30335834/6913c1f8-4a6e-47da-a0e9-fb4b5e3baa7b)

**Comment by xlivans** [comment]
免驱卡 不存在驱动问题 找一下其他原因
