### ISSUE TITLE
请问, DW1820A的驱动有教程吗

### ISSUE THREAD

**Issue by ruanimal** [daliansky/Lenovo-Air13-IWL-Hackintosh#3]
如题, 我X250也用DW1820A目前驱动不正常, 多谢

**Comment by daliansky** [comment]
下载EFI看下不就清楚了嘛

**Comment by ruanimal** [comment]
安装git上安装了这些kext， 改了clover配置，蓝牙能够正常驱动，但是wifi让系统卡死了。 

1. 加了这几个kext，`AirportBrcmFixup, BrcmFirmwareData, BrcmPatchRAM2, HoRNDIS.kext`
2. clover boot  `brcmfx-driver=1 brcmfx-country=#a`
3. clover devices
```
			<key>PciRoot(0x0)/Pci(0x1c,0x0)/Pci(0x0,0x0)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>WLAN</string>
				<key>compatible</key>
				<string>pci14e4,4353</string>
				<key>device_type</key>
				<string>Airport Extreme</string>
				<key>model</key>
				<string>DW1820A (BCM4350) 802.11ac Wireless</string>
				<key>name</key>
				<string>Airport</string>
			</dict>
```
![image](https://user-images.githubusercontent.com/14031394/59005568-b8c21880-8850-11e9-84e7-911185ac07aa.png)
看这个截图，设备id感觉不对

**Comment by ruanimal** [comment]
这个是的clover， 帮忙看看

[https://share.weiyun.com/5k2Q6fF](https://share.weiyun.com/5k2Q6fF)

@daliansky

**Comment by ruanimal** [comment]
![image](https://user-images.githubusercontent.com/14031394/59040717-dec7d700-88a9-11e9-9b21-6aa408ede32d.png)
是因为这个卡序号和你的不一样吗？

**Comment by ruanimal** [comment]
https://osxlatitude.com/forums/topic/11322-broadcom-bcm4350-cards-under-high-sierramojave/ 

DW1820A真的是个神坑

**Comment by ghost** [comment]
小兵 希望出一个教程

**Comment by ghost** [comment]
我也希望有个教程 感觉很多人图便宜 买了dw1820a 其它M2接口的网卡都好贵啊

**Comment by FuckDoctors** [comment]
照着EFI设了仍然不行。。
