### ISSUE TITLE
Release 1.4.0版本中 Command 与Option 位置不对

### ISSUE THREAD

**Issue by ApsarasX** [daliansky/Lenovo-Air13-IWL-Hackintosh#6]
1.2.0版本中修复了Command 与Option 位置互换的问题，但是最新的1.4.0版本又给换了回来

**Comment by youngerruan** [comment]
> 1.2.0版本中修复了Command 与Option 位置互换的问题，但是最新的1.4.0版本又给换了回来

自己改改，ps2controller.kext里面，有个plist，里面找到swap opinion and command 值
