### ISSUE TITLE
What's the purpose of SSDT-EC.aml ?

### ISSUE THREAD

**Issue by ettingshausen** [daliansky/Lenovo-Air13-IWL-Hackintosh#7]
https://github.com/daliansky/Lenovo-Air13-IWL-Hackintosh/blob/6e31cc51fd5850e415d8389655cb7d4a3e8d1b78/HotPatch/SSDT-EC.dsl#L8  

I'm using a copy of EFI from internet. I found  without `SSDT-EC.aml ` catalina won't boot. This file seems quit simple.  What's the purpose of it?

**Comment by xlivans** [comment]
For the 10.15+ system [notebook], if the EC controller name is not EC, SSDT-EC needs to be added, otherwise the system crashes during the startup phase.
